
project_id = "nluwegaxtjekbpccjuxt"

[global.env]
SUPABASE_URL = "env:SUPABASE_URL"
SUPABASE_SERVICE_ROLE_KEY = "env:SUPABASE_SERVICE_ROLE_KEY"
ZOHO_CLIENT_ID = "1000.3S7ZZ1UUOBK9LM2JB1F6FI3GCB1QZN"
ZOHO_CLIENT_SECRET = "env:ZOHO_CLIENT_SECRET"
STRIPE_SECRET_KEY = "env:STRIPE_SECRET_KEY"
STRIPE_EMPLOYER_PRICE_ID = "env:STRIPE_EMPLOYER_PRICE_ID" 
STRIPE_WEBHOOK_SECRET = "env:STRIPE_WEBHOOK_SECRET"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false
