
project_id = "nluwegaxtjekbpccjuxt"

[global.env]
SUPABASE_URL = "env:SUPABASE_URL"
SUPABASE_SERVICE_ROLE_KEY = "env:SUPABASE_SERVICE_ROLE_KEY"
ZOHO_CLIENT_ID = "1000.TZT452YC0W145Y78W51ESL0JON7W2E"
ZOHO_CLIENT_SECRET = "env:ZOHO_CLIENT_SECRET"
