
# This file configures your Netlify deployment

# The following redirect is necessary for SPAs using client-side routing
# It forwards all requests to index.html, letting your React Router handle them
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Basic build settings
[build]
  publish = "dist"
  command = "npm run build"

# Set environment variables for production
[build.environment]
  NODE_VERSION = "18"

# Add cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add cache control for HTML and JSON
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
